version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install --save @types/express @types/express-serve-static-core @types/multer
      - npm install -g @nestjs/cli

  pre_build:
    commands:
      - echo "Running database migration..."
      - npm run migration:run

  build:
    commands:
      - echo "Building NestJS application..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - node_modules/**/*
    - appspec.yml
    - dist/**/*
    - scripts/**/*
    - package.json
    - package-lock.json

cache:
  paths:
    - 'node_modules/**/*'
